# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            UDA_S3_STACK_NAME=saa-"${CIRCLE_WORKFLOW_ID:0:7}" 
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name $UDA_S3_STACK_NAME \
              --parameter-overrides NAME=$UDA_S3_STACK_NAME
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Clean Up Previous Stack
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > export_file
            cat export_file
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: Promote to Production
        command: |
          echo $UDA_S3_STACK_NAME
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${UDA_S3_STACK_NAME}"

# workflow
workflows:
  cci_workflow:
    jobs:
      - create_and_deploy_front_end
      - clean_up_old_front_end:
          requires:
            - create_and_deploy_front_end
