# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            UDA_S3_STACK_NAME="${CIRCLE_WORKFLOW_ID:0:7}"
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name saa-"${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides saa-"${CIRCLE_WORKFLOW_ID:0:7}"
  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: mkdir -p workspace
      - run:
          name: Clean Up Previous Stack
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > workspace/export_file
      - persist_to_workspace:
          root: workspace
          paths:
            - export_file
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: Promote to Production
        command: |
          echo $UDA_S3_STACK_NAME
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${UDA_S3_STACK_NAME}"
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Clean Up
          command: |
            PreviousPipelineID=$(cat /tmp/workspace/export_file)
            aws s3 rm "s3://${PreviousPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"

# workflow
workflows:
  cci_workflow:
    context: udacity-items
    jobs:
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - promote_to_production
