# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name rollback
          when: on_fail
  

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file ec2_simple.yml \
              --stack-name rollback
      - run: return 1
      - destroy_environment

workflows:
  cci_workflow:
    jobs:
      - create_infrastructure
          context: udacity-items