# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            export MY_ENV_VAR="${CIRCLE_WORKFLOW_ID:0:7}"
            echo $MY_ENV_VAR 
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name $MY_ENV_VAR \
              --parameter-overrides NAME=$MY_ENV_VAR
    
  # create_and_deploy_front_end:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file bucket.yml \
  #             --stack-name ${CIRCLE_WORKFLOW_ID:0:7} \
  #             --parameter-overrides PipelineID=${CIRCLE_WORKFLOW_ID:0:7},NAME=TheBigTest

workflows:
  cci_workflow:
    jobs:
      - create_and_deploy_front_end
