# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name p"${CIRCLE_WORKFLOW_ID:0:7}"
          when: on_fail

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name p"${CIRCLE_WORKFLOW_ID:0:7}"\
              --parameter-overrides NAME=p"${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync index.html s3://p"${CIRCLE_WORKFLOW_ID:0:7}" --delete
  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: mkdir -p workspace
      - run:
          name: Get Previous PipelinID
          command: |
            yum install tar -y
            yum install gzip -y
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > workspace/export_file
      - persist_to_workspace:
          root: workspace
          paths:
            - export_file
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: Promote to Production
        command: |
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID=p"${CIRCLE_WORKFLOW_ID:0:7}"
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Instal workspace dependecies
          command: |
            yum install tar -y
            yum install gzip -y
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Clean Up Previous Stack
          command: |
            PreviousPipelineID=$(cat /tmp/workspace/export_file)
            aws s3 rm "s3://${PreviousPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"

# workflow
workflows:
  cci_workflow:
    jobs:
      - create_and_deploy_front_end:
          context: udacity-items
      - get_last_deployment_id:
          context: udacity-items
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          context: udacity-items
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          context: udacity-items
          requires:
            - promote_to_production
